name: Docker Image CI

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile*"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile*"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract the Caddy version numbers from the Dockerfile
        run: bash .github/version_extractor.sh ./Dockerfile >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            axistools/caddy-bundle:${{ env.CADDY_MAJOR }}.${{ env.CADDY_MINOR }}.${{ env.CADDY_PATCH }}
            axistools/caddy-bundle:${{ env.CADDY_MAJOR }}.${{ env.CADDY_MINOR }}
            axistools/caddy-bundle:${{ env.CADDY_MAJOR }}
            axistools/caddy-bundle:latest
